### ISSUE TITLE
Shutdown handleFatalError doesn't work with @suppressed errors

### ISSUE THREAD

**Issue by ruudk** [hautelook/sentry-client#20]
See original [Symfony issue](https://github.com/symfony/symfony/issues/20901)

Every time I deployed my application it would always complain with this error:

```
Symfony\Component\Debug\Exception\FatalErrorException: include(): Failed opening '/home/ticketswap/app/releases/20161213142627/app/cache/prod/annotations.php' for inclusion (include_path='.:/usr/share/php')
#1 /vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php(331): null
#0 Hautelook\SentryClient\ErrorHandler(null): Hautelook\SentryClient\ErrorHandler::handleFatalError
```

But the error supposed to be suppressed with a `@`. 

Why does this client registers the shutdown handler to fetch the last occurred PHP error? 

Is this old code? It doesn't work with suppression.

Can I submit a PR to remove it?

**Comment by nicolas-grekas** [comment]
The shutdown hander is here to catch fatal errors. Which means it should deal only with `E_PARSE | E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR`

**Comment by ruudk** [comment]
@nicolas-grekas Ah, I see. Any suggestions on how to approach this problem?

**Comment by nicolas-grekas** [comment]
check the type as returned by error_get_last and "return" if it's not one of these types?

**Comment by ruudk** [comment]
@nicolas-grekas Like this? https://github.com/hautelook/sentry-client/pull/21
