### ISSUE TITLE
[PHP 7] Support throwables of type \Error

### ISSUE THREAD

**Issue by ruudk** [hautelook/sentry-client#23]
I just got a [TypeError](http://php.net/manual/en/class.typeerror.php) on a PHP 7.1 server that was catched and send to `client->captureException`.

Since the `captureException` only allows `\Exception` it failed.

What would be the best way to support these errors? Should I just extend the `captureException` and allow it any `Throwable`? Or should I copy them, and add `captureError` etc.

Do I need to add `ignored_errors` method as well?

**Comment by ruudk** [comment]
@hjr3 Do you have an idea about this? I'm willing to create a PR so that this library is PHP 7 ready :) Let me know!

**Comment by hjr3** [comment]
@ruudk I did some research on this and based on http://php.net/set_exception_handler I think we should extend `captureException` to allow any `Throwable`. Did you want to do this in a backwards compatible way or should we break BC?

We can also add `ignored_errors`, but it can be a separate PR too.

**Comment by ruudk** [comment]
@hjr3 I can have a look at this, but would be nice to first have my other PR's merged :)

**Comment by hjr3** [comment]
@ruudk apologies, I missed the notifications. I will def review the others in a bit.

**Comment by hjr3** [comment]
@ruudk can you message me on twitter (@hermanradtke) or suggest another way I can ping you?
